'use strict';
window.CellSaves=(()=>{
  const E=window.CellEngine,C=window.CellContent,KEY='cell-command-v1',MAX_BYTES=1024*1024;
  const finite=(x,min,max)=>typeof x==='number'&&Number.isFinite(x)&&x>=min&&x<=max;
  const integer=(x,min,max)=>Number.isInteger(x)&&finite(x,min,max);
  const check=(condition)=>{if(!condition)throw new Error('This save contains missing or invalid game data.');};
  function validate(raw){
    check(raw&&raw.format==='cell-command-save'&&[1,2,3].includes(raw.formatVersion)&&raw.state);
    if(raw.formatVersion===1)return E.migrate(window.CellSavesLegacy.validate(raw));
    const a=raw.state,s=E.fresh();check([2,3].includes(a.version)&&finite(a.elapsed,0,1e8)&&['playing','won','rescue'].includes(a.status));
    check(finite(a.health,0,100)&&integer(a.nextId,1,1e8)&&integer(a.seed,0,4294967295));
    for(const k of Object.keys(s.resources)){check(a.resources&&finite(a.resources[k],0,1200));s.resources[k]=a.resources[k];}
    const ids=new Set();const base=b=>{check(b&&integer(b.id,1,a.nextId-1)&&!ids.has(b.id)&&finite(b.x,0,E.WORLD.w)&&finite(b.y,0,E.WORLD.h));ids.add(b.id);};
    const target=t=>{if(t===null)return null;check(t&&['move','port','building','focus','enemy'].includes(t.kind));if(t.kind==='move'){check(finite(t.x,0,E.WORLD.w)&&finite(t.y,0,E.WORLD.h));return {kind:'move',x:t.x,y:t.y};}check(integer(t.id,1,a.nextId-1));return {kind:t.kind,id:t.id};};
    check(Array.isArray(a.buildings)&&a.buildings.length>=5&&a.buildings.length<=55);
    s.buildings=a.buildings.map(b=>{base(b);check(Object.hasOwn(C.buildings,b.type)&&finite(b.progress,0,1)&&finite(b.clock,0,1e5)&&finite(b.hp,0,C.buildings[b.type].hp)&&typeof b.auto==='boolean'&&Array.isArray(b.queue)&&b.queue.length<=5);const queue=b.queue.map(q=>{check(q&&Object.hasOwn(C.units,q.kind)&&C.units[q.kind].producer===b.type&&finite(q.remaining,0,C.units[q.kind].time));return {kind:q.kind,remaining:q.remaining};});let research=null;if(b.research){check(Object.hasOwn(C.research,b.research.key)&&C.research[b.research.key].at===b.type&&finite(b.research.remaining,0,C.research[b.research.key].time));research={key:b.research.key,remaining:b.research.remaining};}let rally=null;if(b.rally){check(finite(b.rally.x,0,E.WORLD.w)&&finite(b.rally.y,0,E.WORLD.h)&&['move','port'].includes(b.rally.kind));rally={x:b.rally.x,y:b.rally.y,kind:b.rally.kind,id:integer(b.rally.id,1,a.nextId-1)?b.rally.id:null};}return {id:b.id,type:b.type,x:b.x,y:b.y,progress:b.progress,clock:b.clock,hp:b.hp,queue,research,rally,auto:b.auto,infected:false};});
    for(const type of ['nucleus','mitochondrion','ribosome','golgi','lysosome'])check(s.buildings.some(b=>b.type===type&&b.progress===1));
    for(const type of Object.keys(C.buildings))check(s.buildings.filter(b=>b.type===type).length<=C.buildings[type].limit);
    check(Array.isArray(a.units)&&a.units.length<=72);
    const orders=['auto','guard','gather','move','attackmove','hold','attack','build','repair'];
    s.units=a.units.map(u=>{base(u);check(Object.hasOwn(C.units,u.type)&&orders.includes(u.order)&&finite(u.hp,0,C.units[u.type].hp)&&integer(u.cargo,0,1));check(u.anchor&&finite(u.anchor.x,0,E.WORLD.w)&&finite(u.anchor.y,0,E.WORLD.h));check(Array.isArray(u.orders)&&u.orders.length<=10);const queued=u.orders.map(o=>{check(o&&orders.includes(o.order));return {order:o.order,target:target(o.target)};});check(u.cargoType===null||['glucose','amino','lipid','nucleotide','mixed'].includes(u.cargoType));return {id:u.id,type:u.type,x:u.x,y:u.y,hp:u.hp,target:target(u.target),order:u.order,orders:queued,anchor:{x:u.anchor.x,y:u.anchor.y},site:integer(u.site,1,a.nextId-1)?u.site:null,cargo:u.cargo,cargoType:u.cargoType,path:[],pathClock:0,clock:0,fx:0};});
    check(Array.isArray(a.ports)&&a.ports.length>=3&&a.ports.length<=16);s.ports=a.ports.map(p=>{base(p);check(['glucose','amino','lipid','nucleotide'].includes(p.type)&&integer(p.stock,0,100)&&finite(p.clock,0,10)&&(p.renewable===undefined||typeof p.renewable==='boolean'));return {id:p.id,type:p.type,x:p.x,y:p.y,stock:p.stock,clock:p.clock,renewable:p.renewable!==false};});
    check(Array.isArray(a.foci)&&a.foci.length<=6);s.foci=a.foci.map(f=>{base(f);check(['core','assembly','replication'].includes(f.kind)&&[190,420].includes(f.maxHealth)&&finite(f.health,0,f.maxHealth)&&finite(f.clock,0,1e8));return {id:f.id,kind:f.kind,x:f.x,y:f.y,health:f.health,maxHealth:f.maxHealth,clock:f.clock,replication:0};});
    check(Array.isArray(a.viruses)&&a.viruses.length<=12);s.viruses=a.viruses.map(v=>{base(v);const kind=v.kind===undefined?'cargo':v.kind;check(Object.hasOwn(C.enemyTypes,kind)&&finite(v.hp,0,C.enemyTypes[kind].hp));return {id:v.id,kind,x:v.x,y:v.y,hp:v.hp,maxHp:C.enemyTypes[kind].hp,target:integer(v.target,1,a.nextId-1)?v.target:null,path:[],pathClock:0};});
    check(a.ai&&finite(a.ai.reserve,0,70)&&finite(a.ai.next,0,1e9)&&finite(a.ai.nextExpand,0,1e9)&&integer(a.ai.spawned,0,1e8)&&integer(a.ai.replications,0,1e8)&&typeof a.ai.coreDestroyed==='boolean');s.ai={reserve:a.ai.reserve,next:a.ai.next,spawned:a.ai.spawned,replications:a.ai.replications,nextExpand:a.ai.nextExpand,coreDestroyed:a.ai.coreDestroyed};
    for(const k of Object.keys(s.stats)){check(a.stats&&integer(a.stats[k],0,1e8));s.stats[k]=a.stats[k];}
    check(Array.isArray(a.learned)&&a.learned.length<=C.questions.length&&a.learned.every(id=>C.questions.some(q=>q.id===id))&&new Set(a.learned).size===a.learned.length);s.learned=[...a.learned];
    check(a.quiz&&integer(a.quiz.index,0,C.questions.length)&&finite(a.quiz.next,0,1e9));check(a.quiz.pending===null||integer(a.quiz.pending,0,C.questions.length-1));if(a.quiz.pending!==null)check(a.quiz.pending===a.quiz.index);s.quiz={index:a.quiz.index,pending:null,next:1e9,tries:0};
    check(a.settings&&[.65,1,1.35].includes(a.settings.speed)&&typeof a.settings.reducedMotion==='boolean'&&typeof a.settings.revealMap==='boolean');s.settings={speed:a.settings.speed,reducedMotion:a.settings.reducedMotion,revealMap:a.settings.revealMap};
    for(const k of Object.keys(s.tutorial)){check(a.tutorial&&typeof a.tutorial[k]==='boolean');s.tutorial[k]=a.tutorial[k];}
    check(integer(a.tier,1,4)&&Array.isArray(a.upgrades)&&a.upgrades.length<=6&&a.upgrades.every(k=>['motors','cargo','respiration','response','stability','reach'].includes(k))&&new Set(a.upgrades).size===a.upgrades.length);s.tier=a.tier;s.upgrades=[...a.upgrades];
    check(Array.isArray(a.explored)&&a.explored.length===E.COLS*E.ROWS&&a.explored.every(n=>n===0||n===1));s.explored=[...a.explored];
    check(a.groups&&typeof a.groups==='object'&&!Array.isArray(a.groups)&&Object.keys(a.groups).length<=9);s.groups={};for(const [key,arr] of Object.entries(a.groups)){check(/^[1-9]$/.test(key)&&Array.isArray(arr)&&arr.length<=128&&arr.every(n=>integer(n,1,a.nextId-1)));s.groups[key]=[...arr];}
    check(a.formation===undefined||['line','box','spread'].includes(a.formation));s.formation=a.formation||'line';s.version=3;s.elapsed=a.elapsed;s.status=a.status;s.health=a.health;s.nextId=a.nextId;s.seed=a.seed;s.repairClock=finite(a.repairClock,0,10)?a.repairClock:0;s.victorySeen=a.victorySeen===true;s.navRevision=0;
    s.studentName=typeof a.studentName==='string'?a.studentName.slice(0,60):'';s.startedAt=typeof a.startedAt==='string'?a.startedAt.slice(0,40):s.startedAt;s.events=[];E.event(s,'Save loaded. Your RTS match is ready to continue.','good');return s;
  }
  const envelope=s=>({format:'cell-command-save',formatVersion:3,savedAt:new Date().toISOString(),state:E.clone(s)});
  function save(s){try{localStorage.setItem(KEY,JSON.stringify(envelope(s)));return true;}catch{return false;}}
  function load(){try{const str=localStorage.getItem(KEY);return str?validate(JSON.parse(str)):null;}catch{return null;}}
  function download(name,text,type='application/json'){const blob=new Blob([text],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function exportSave(s){download('cell-command-save.json',JSON.stringify(envelope(s),null,2));}
  async function importFile(file){if(!file||file.size>MAX_BYTES)throw new Error('Choose a Cell Command save smaller than 1 MB.');return validate(JSON.parse(await file.text()));}
  function encodeReport(r){const bytes=new TextEncoder().encode(JSON.stringify(r));return btoa(Array.from(bytes,b=>String.fromCharCode(b)).join('')).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
  function decodeReport(encoded){check(typeof encoded==='string'&&encoded.length<=12000&&/^[\w-]+$/.test(encoded));const str=atob(encoded.replace(/-/g,'+').replace(/_/g,'/'));const r=JSON.parse(new TextDecoder().decode(Uint8Array.from(str,c=>c.charCodeAt(0))));check(r&&r.format==='cell-command-report'&&r.version===1&&typeof r.name==='string'&&r.name.length<=60&&typeof r.created==='string'&&r.created.length<=40&&['Cell stabilized','Recovery needed','In progress'].includes(r.status));for(const key of ['seconds','deliveries','organelles','defenders','infections'])check(integer(r[key],0,1e8));check(integer(r.growth,0,100)&&integer(r.health,0,100));for(const key of ['questions','attempts','firstTry'])if(r[key]!==undefined)check(integer(r[key],0,1e8));if(r.concepts!==undefined)check(Array.isArray(r.concepts)&&r.concepts.length<=C.questions.length&&r.concepts.every(v=>typeof v==='string'&&v.length<=80));if(r.tier!==undefined)check(integer(r.tier,1,4));if(r.upgrades!==undefined)check(Array.isArray(r.upgrades)&&r.upgrades.length<=6&&r.upgrades.every(v=>typeof v==='string'&&v.length<=80));return r;}
  return {KEY,MAX_BYTES,validate,envelope,save,load,download,exportSave,importFile,encodeReport,decodeReport};
})();
