const {chromium}=require('playwright');const fs=require('fs'),path=require('path'),http=require('http'),assert=require('node:assert/strict');
const project=path.resolve(__dirname,'..'),output=fs.mkdtempSync(path.join(require('os').tmpdir(),'newton-attachments-'));
const server=http.createServer((req,res)=>{try{const url=new URL(req.url,'http://localhost'),file=path.join(project,url.pathname==='/'?'index.html':url.pathname);res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.NEWTON_CHROMIUM?{executablePath:process.env.NEWTON_CHROMIUM}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.NewtonApp);
 await page.evaluate(()=>{scene=N.empty();scene.gravity=0;const hull=N.body('rectangle',0,3,{w:2,h:1,mass:2}),fuel=N.equipment('fuel',5,3,{contents:1}),oxygen=N.equipment('oxygen',6.5,3,{contents:8}),engine=N.equipment('thruster',8,3);engine.thrusters[0].angle=0;scene.bodies=[hull,fuel,oxygen,engine];selected=trackedId=hull.id;window.parts={hull:hull.id,fuel:fuel.id,oxygen:oxygen.id,engine:engine.id};changed();camera={x:3,y:3,scale:55};});
 const canvas=await page.locator('#worldCanvas').boundingBox();
 async function dragPart(kind,x,y){const from=await page.evaluate(kind=>{const b=scene.bodies.find(b=>b.id===parts[kind]);return screenPoint(b.x,b.y)},kind),to=await page.evaluate(({x,y})=>screenPoint(x,y),{x,y});await page.mouse.move(canvas.x+from.x,canvas.y+from.y);await page.mouse.down();await page.mouse.move(canvas.x+to.x,canvas.y+to.y,{steps:5});await page.mouse.up();}
 await dragPart('fuel',1.6,3);assert.ok(await page.evaluate(()=>scene.bodies.find(b=>b.id===parts.fuel).mountId===parts.hull));
 await dragPart('oxygen',2.3,3);assert.ok(await page.evaluate(()=>scene.bodies.find(b=>b.id===parts.oxygen).mountId===parts.fuel));
 await dragPart('engine',3,3);assert.ok(await page.evaluate(()=>scene.bodies.find(b=>b.id===parts.engine).mountId===parts.oxygen));
 assert.equal(await page.evaluate(()=>sim.resources(parts.engine).fuel),1);assert.equal(await page.evaluate(()=>sim.resources(parts.engine).oxygen),8);
 console.log('PASS pointer-drop snapping into a hull → fuel → oxygen → engine chain');
 const before=await page.evaluate(()=>scene.bodies.map(b=>({id:b.id,x:b.x,y:b.y})));await page.evaluate(()=>{selected=parts.hull;updateInspector();});await dragPart('hull',1,3);const after=await page.evaluate(()=>scene.bodies.map(b=>({id:b.id,x:b.x,y:b.y})));for(let i=0;i<before.length;i++){assert.ok(Math.abs(after[i].x-before[i].x-1)<1e-8);assert.ok(Math.abs(after[i].y-before[i].y)<1e-8);}
 console.log('PASS dragging the host carries nested equipment');
 await page.evaluate(()=>{selected=parts.engine;updateInspector();$('followToggle').checked=true;});await page.screenshot({path:output+'/equipment-paused.png'});
 await page.locator('#runButton').click();await page.keyboard.down('w');await page.waitForFunction(()=>sim.time>.2&&sim.bodies.get(parts.engine).activeThrusters.length>0);await page.screenshot({path:output+'/equipment-burning.png'});assert.ok(await page.evaluate(()=>sim.resources(parts.engine).fuel<1&&sim.resources(parts.engine).oxygen<8&&sim.state(parts.hull).vx>0));await page.keyboard.up('w');await page.waitForFunction(()=>sim.bodies.get(parts.engine).activeThrusters.length===0);await page.locator('#runButton').click();console.log('PASS mapped thrust consumes both tanks; releasing key stops flame and force');
 await page.locator('#fuelLevelsToggle').uncheck();assert.equal(await page.locator('[aria-label="Fuel remaining"]').count(),0);assert.equal(await page.locator('[aria-label="Oxygen remaining"]').count(),1);await page.locator('#oxygenLevelsToggle').uncheck();assert.equal(await page.locator('#resourceHud').isVisible(),false);await page.reload();await page.waitForFunction(()=>window.NewtonApp);assert.equal(await page.locator('#fuelLevelsToggle').isChecked(),false);assert.equal(await page.locator('#oxygenLevelsToggle').isChecked(),false);await page.locator('#fuelLevelsToggle').check();await page.locator('#oxygenLevelsToggle').check();
 await page.evaluate(()=>{window.parts=Object.fromEntries(['fuel','oxygen','thruster'].map(k=>[k==='thruster'?'engine':k,scene.bodies.find(b=>b.kind===k).id]));selected=parts.fuel;updateInspector();});await page.locator('#detachEquipment').click();assert.equal(await page.evaluate(()=>sim.resources(parts.engine).fuel),0);await page.locator('#runButton').click();await page.keyboard.down('w');await page.waitForFunction(()=>sim.time>.1);assert.equal(await page.evaluate(()=>sim.bodies.get(parts.engine).activeThrusters.length),0);await page.keyboard.up('w');await page.locator('#resetButton').click();
 await page.evaluate(()=>{selected=parts.fuel;updateInspector();});assert.equal(await page.locator('#attachEquipment').isEnabled(),true);await page.locator('#attachEquipment').click();assert.equal(await page.evaluate(()=>sim.resources(parts.engine).fuel),1);await page.evaluate(()=>N.validate(scene));console.log('PASS Detach cuts fuel supply; Attach nearby restores it; level preferences persist');
 // Keep the descendant assembly attached when selecting a different host.
 await page.evaluate(()=>{const root=scene.bodies.find(b=>b.kind==='oxygen');selected=root.id;updateInspector();});const hostId=await page.evaluate(()=>scene.bodies.find(b=>b.kind==='rectangle').id);await page.locator('#equipmentMount').selectOption(hostId);assert.equal(await page.evaluate(()=>sim.resources(parts.engine).fuel),1);
 const cycle=await page.evaluate(()=>{const root=scene.bodies.find(b=>b.kind==='oxygen'),engine=scene.bodies.find(b=>b.kind==='thruster');return attachEquipment(root.id,engine.id);});assert.equal(cycle,false);
 await page.setViewportSize({width:390,height:844});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:output+'/equipment-mobile.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS remounting, cycle prevention and mobile layout; screenshots:',output);
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1}).finally(()=>server.close());
