const {chromium}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const project=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{try{const u=new URL(req.url,'http://localhost'),f=path.join(project,u.pathname==='/'?'index.html':u.pathname);res.setHeader('Content-Type',f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,...(process.env.NEWTON_CHROMIUM?{executablePath:process.env.NEWTON_CHROMIUM}:{}),args:['--no-sandbox','--disable-gpu','--disable-dev-shm-usage']});try{
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.NewtonApp);
 await page.evaluate(()=>{scene=N.empty();scene.gravity=0;scene.bodies=[N.body('rectangle',0,3,{w:2,h:1,mass:2,fx:4})];selected=scene.bodies[0].id;changed();camera={x:0,y:3,scale:55};window.constructorCount=0;const Original=N.Simulation;N.Simulation=class extends Original{constructor(...args){super(...args);constructorCount++;}};});
 const box=await page.locator('#worldCanvas').boundingBox(),p=await page.evaluate(()=>screenPoint(0,3));await page.mouse.move(box.x+p.x,box.y+p.y);await page.mouse.down();await page.mouse.move(box.x+p.x+110,box.y+p.y,{steps:25});
 assert.equal(await page.evaluate(()=>constructorCount),0);assert.equal(await page.evaluate(()=>sim.previewing),true);assert.ok(await page.evaluate(()=>Math.abs(sim.state(selected).x-2)<.01));await page.mouse.up();assert.equal(await page.evaluate(()=>constructorCount),1);assert.equal(await page.evaluate(()=>sim.previewing),false);console.log('PASS 25 pointer moves preview without constructing worlds; release commits once');
 const graph=await page.evaluate(()=>{const pool=graphData;for(let i=0;i<48000;i++){sim.step();sampleGraph();}const rows=Array.from(graphData);return {length:rows.length,first:rows[0].t,last:rows.at(-1).t,ordered:rows.every((r,i)=>!i||r.t>rows[i-1].t),error:Math.abs(rows.at(-1).vx-2*rows.at(-1).t),same:pool===graphData};});
 assert.equal(graph.length,3600);assert.ok(graph.ordered&&graph.same&&graph.first>0&&graph.last>199);assert.ok(graph.error<1e-7);await page.locator('#graphToggle').check();const download=page.waitForEvent('download');await page.locator('#csvButton').click();const csv=fs.readFileSync(await (await download).path(),'utf8').trim().split('\n');assert.equal(csv.length,3601);assert.ok(Number(csv.at(-1).split(',')[0])>Number(csv[1].split(',')[0]));console.log('PASS 200 simulation seconds wrap a fixed 3,600-row graph buffer; CSV remains chronological');
 const undo=await page.evaluate(()=>{history=[];checkpoint.bytes=0;scene=N.empty();scene.bodies=[N.body('circle',0,3)];for(let i=0;i<60;i++){scene.bodies[0].mass=i+1;checkpoint();}const capped=history.length===30;$('undoButton').onclick();const restored=scene.bodies[0].mass===60;history=[];checkpoint.bytes=0;const huge='x'.repeat(1600000);scene.notes=huge;for(let i=0;i<10;i++)checkpoint();const bounded=checkpoint.bytes<=8*1024*1024&&history.length>0&&checkpoint.bytes===history.reduce((n,s)=>n+s.length*2,0);history=[];checkpoint.bytes=0;delete scene.notes;changed();return {capped,restored,bounded};});assert.deepEqual(undo,{capped:true,restored:true,bounded:true});console.log('PASS undo retains at most 30 snapshots and respects its serialized memory budget');
 await page.waitForTimeout(300);await page.evaluate(()=>{window.domChanges=0;window.displayObserver=new MutationObserver(changes=>domChanges+=changes.length);for(const id of ['measurements','resourceHud','zoomReadout']){const el=$(id);if(el)displayObserver.observe(el,{subtree:true,childList:true,characterData:true,attributes:true});}});await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>domChanges),0);await page.evaluate(()=>displayObserver.disconnect());console.log('PASS paused unchanged measurements and meters produce no DOM mutations');
 const cdp=await page.context().newCDPSession(page);async function memory(){await cdp.send('HeapProfiler.collectGarbage');return (await cdp.send('Runtime.getHeapUsage')).usedSize;}
 // Warm up actual engine creation/removal paths before taking heap snapshots.
 async function churn(){return page.evaluate(()=>{for(let cycle=0;cycle<25;cycle++){scene=N.empty();scene.gravity=0;const launcher=N.body('launcher',0,3,{fixed:true,w:1,h:1,launchSpeed:10,launchAngle:0,projectileMass:.1,projectileRadius:.1,fireKey:'f',aimPositiveKey:'a',aimNegativeKey:'d',aimRate:30,muzzleOffset:1.1});scene.bodies=[launcher];selected=launcher.id;rebuild();for(let i=0;i<100;i++)sim.fire(launcher.id);for(const id of [...sim.shots])sim.removeProjectile(id);if(sim.world.getBodyCount()!==2||sim.dynamicBodies.length||sim.shots.length)throw Error('Projectile retention');}return graphData.capacity;});}
 await churn();await page.waitForTimeout(1200);const heap=[];for(let i=0;i<3;i++){await churn();await page.waitForTimeout(100);heap.push(await memory());}assert.ok(heap[2]-heap[0]<3*1024*1024,'Repeated cleanup should not retain megabytes of engine worlds');assert.deepEqual(errors,[]);console.log('PASS repeated scene/projectile cleanup; post-GC heap bytes:',JSON.stringify(heap));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>server.close());
