const assert=require('node:assert/strict');
const N=require('../physics.js');const C=require('../challenges.js');
let tests=0;function test(name,fn){fn();tests++;console.log('PASS',name);}function near(actual,expected,tol){assert.ok(Math.abs(actual-expected)<=tol,`${actual} vs ${expected} ± ${tol}`);}
function sim(extra,g=0){const s=N.empty();s.gravity=g;s.bodies=[N.body('circle',0,0,{r:.5,mass:2,...extra})];return new N.Simulation(s);}
test('F = ma; semi-implicit constant-acceleration position error within one step',()=>{const s=sim({fx:12});s.advance(2);const a=s.state(s.scene.bodies[0].id);near(a.vx,12,1e-9);near(a.ax,6,1e-8);near(a.x,12,6*2*N.DT/2+1e-9);});
test('Gravity is independent of mass',()=>{const a=sim({mass:1},9.81),b=sim({mass:90},9.81);a.advance(1);b.advance(1);near(a.state(a.scene.bodies[0].id).vy,-9.81,1e-9);near(a.state(a.scene.bodies[0].id).y,b.state(b.scene.bodies[0].id).y,1e-9);});
test('Balanced upward force produces a hover',()=>{const s=sim({fy:19.62},9.81);s.advance(2);near(s.state(s.scene.bodies[0].id).y,0,1e-9);});
test('Zero-force velocity is conserved',()=>{const s=sim({vx:3,vy:-2});s.advance(3);const a=s.state(s.scene.bodies[0].id);near(a.x,9,1e-9);near(a.y,-6,1e-9);near(a.distance,3*Math.sqrt(13),1e-8);});
test('Quadratic drag reaches predicted terminal speed',()=>{const s=sim({mass:25/9.81,dragK:1},9.81);s.scene.air=true;s.advance(5);near(s.state(s.scene.bodies[0].id).speed,5,.005);});
test('Off-center thrust produces the expected torque and angular acceleration',()=>{const s=sim({thrusters:[{force:10,angle:0,always:true,key:'d',offsetX:0,offsetY:.2}]});const e=s.bodies.get(s.scene.bodies[0].id);const I=e.body.getInertia();s.step();near(e.body.getAngularVelocity(),-2/I*N.DT,1e-8);});
test('Fast projectile hits a thin fixed wall using CCD',()=>{const s=N.empty();s.gravity=0;const ball=N.body('circle',-2,0,{r:.06,vx:100,restitution:0});s.bodies=[ball,N.body('ground',0,0,{w:.1,h:10,restitution:0})];const q=new N.Simulation(s);q.advance(.1);assert.ok(q.state(ball.id).x<0);near(q.state(ball.id).vx,0,.001);});
test('Invalid scenes are rejected',()=>{assert.throws(()=>N.validate({version:1,bodies:[],joints:[],gravity:Infinity}));const s=N.demo();s.bodies[0].mass=-1;assert.throws(()=>N.validate(s));});
test('A resting body has upward support equal to its weight and zero net force',()=>{const scene=N.empty();const ball=N.body('circle',0,1,{r:.5,mass:3,restitution:0});scene.bodies=[ball,N.body('ground',0,-.5,{w:10,h:1,restitution:0})];const s=new N.Simulation(scene);s.advance(2);const e=s.bodies.get(ball.id);near(e.net.y,0,.001);near(e.reaction.y,29.43,.001);});
test('Halving the time step halves constant-acceleration position error',()=>{const a=sim({fx:12}),b=sim({fx:12});a.advance(1);for(let i=0;i<480;i++)b.step(N.DT/2);const ea=a.state(a.scene.bodies[0].id).x-3,eb=b.state(b.scene.bodies[0].id).x-3;near(ea/eb,2,1e-7);});
const solutions=[4,10,19.62,14,4,3,-12,7.86,Math.sqrt(98.1),Math.asin(98.1/144)*90/Math.PI,25/9.81,30,40,.5,3];
for(let index=0;index<C.levels.length;index++)test(`Level ${index+1}: ${C.levels[index].title} passes with analytic solution`,()=>{const l=C.levels[index],s=new N.Simulation(C.configure(index,solutions[index]));let shot=null,range=null;if(l.metric==='range')shot=s.fire(s.scene.bodies[0].id).spec.id;for(let i=0;i<Math.round(l.duration/N.DT);i++){s.step();if(shot&&range===null){const e=s.bodies.get(shot),p=e.body.getPosition(),q=e.previous;if(s.time>.04&&q.y>0&&p.y<=0&&e.body.getLinearVelocity().y<0){range=q.x+(p.x-q.x)*q.y/(q.y-p.y);}}}const actual=C.observe(index,s,range);assert.ok(C.pass(index,actual),`Result ${actual}, goal ${l.target}`);});
test('Keyboard thrust applies only while its key is held',()=>{const s=sim({thrusters:[{force:10,angle:0,key:'w',always:false,offsetX:0,offsetY:0}]});const id=s.scene.bodies[0].id;s.advance(.1);near(s.state(id).vx,0,1e-9);s.keys.add('w');s.advance(.2);near(s.state(id).vx,1,1e-9);s.keys.clear();s.advance(.2);near(s.state(id).vx,1,1e-9);near(s.state(id).ax,0,1e-9);});
test('Motor keys reverse rotation and release disables drive',()=>{const scene=C.configure(11,30);scene.joints[0].auto=false;const s=new N.Simulation(scene),id=scene.bodies[0].id;s.advance(.1);near(s.state(id).omega,0,1e-8);s.keys.add('d');s.advance(.1);near(s.state(id).omega,Math.PI,1e-7);s.keys.clear();s.step();assert.equal(s.joints.get('motor').joint.isMotorEnabled(),false);s.keys.add('a');s.advance(.1);near(s.state(id).omega,-Math.PI,1e-7);});
test('Meshed gear radii match teeth; remote and incompatible gears are uncoupled',()=>{const scene=C.configure(12,40);assert.ok(N.gearsAdjacent(...scene.bodies));const s=new N.Simulation(scene);assert.ok(s.joints.has('mesh'));s.advance(.3);near(s.state(scene.bodies[0].id).omega+5*s.state(scene.bodies[1].id).omega,0,1e-6);scene.bodies[1].x+=5;assert.equal(new N.Simulation(scene).joints.has('mesh'),false);const incompatible=C.configure(12,40);incompatible.bodies[1].teeth=32;assert.equal(new N.Simulation(incompatible).joints.has('mesh'),false);});
console.log(`${tests} numerical checks passed.`);
