const assert=require('node:assert/strict'),N=require('../physics.js');
require('../workshop.js');require('../world-examples.js');
const near=(a,b,t=1e-8)=>assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`);let count=0;function test(name,f){f();count++;console.log('PASS',name);}
test('Density, thickness and shape area determine mass while legacy masses remain stable',()=>{const b=N.body('rectangle',0,0,{w:2,h:1,mass:3});N.prepareSizing(b,100);N.resizeMass(b);near(b.mass,4);const old=N.copy(b);b.w=4;N.resizeMass(b,old);near(b.mass,8);b.thickness=.04;N.resizeMass(b);near(b.mass,16);const legacy=N.body('circle',0,0,{mass:7});N.prepareSizing(legacy);N.resizeMass(legacy);near(legacy.mass,7);});
test('Engine size scales mass and thrust; three collision fixtures match the nozzle graphics',()=>{const b=N.equipment('thruster',0,0);N.prepareSizing(b,300);N.resizeMass(b);const old=N.copy(b);b.w*=2;b.h*=2;N.resizeMass(b,old);near(b.mass,old.mass*4);near(b.thrusters[0].force,old.thrusters[0].force*4);const s=N.empty();s.gravity=0;s.bodies=[b];const sim=new N.Simulation(s),body=sim.bodies.get(b.id).body;near(body.getMass(),b.mass);let fixtures=0;for(let f=body.getFixtureList();f;f=f.getNext())fixtures++;assert.equal(fixtures,3);});
test('Tank resizing scales dry mass, remaining contents and capacity',()=>{const b=N.equipment('fuel',0,0,{contents:2,capacity:4});N.prepareSizing(b);const old=N.copy(b);b.w*=2;b.h*=2;N.resizeMass(b,old);near(b.mass,old.mass*4);near(b.contents,8);near(b.capacity,16);});
test('Ground, terrain and mounted assemblies can be fixed and unfixed',()=>{for(const kind of ['ground','terrain']){const s=N.empty(),b=kind==='terrain'?N.terrain(0,3,4,16):N.body(kind,0,3);b.fixed=false;s.bodies=[b];N.validate(s);const sim=new N.Simulation(s),e=sim.bodies.get(b.id);near(e.body.getMass(),b.mass);assert.ok(e.body.getInertia()>0);sim.advance(.1);assert.ok(e.body.getPosition().y<3);b.fixed=true;const fixed=new N.Simulation(s);fixed.advance(.1);near(fixed.state(b.id).y,3);}const hull=N.body('rectangle',0,3,{fixed:true}),engine=N.equipment('thruster',0,2,{fixed:true,mountId:hull.id}),s=N.empty();s.bodies=[hull,engine];N.validate(s);});
test('A scaled motor housing contributes dry mass to its chassis and scales torque',()=>{const s=N.empty(),h=N.body('rectangle',0,0,{mass:5}),wheel=N.body('circle',1,0),m=N.body('motor',1,0,{r:.18,mass:.6,mountId:h.id,motorTorque:20});s.bodies=[h,wheel,m];s.joints=[{id:'motor',kind:'axle',a:h.id,b:wheel.id,x:1,y:0,motor:true,rpm:60,torque:20,keyPositive:'d',keyNegative:'a',motorBodyId:m.id}];global.scene=s;N.prepareSizing(m);const old=N.copy(m);m.r*=2;assert.ok(Workshop.resizeBody(m,old));near(m.mass,2.4);near(s.joints[0].torque,80);const sim=new N.Simulation(N.validate(s));near(sim.bodies.get(m.id).body.getMass(),2.4);});
test('Nearby sources obey inverse-square gravity outside a uniform-density core',()=>{const planet=N.body('planet',0,0,{r:2,mass:100/N.G,fixed:true}),s=N.empty();s.gravityModel='planets';s.bodies=[planet];near(N.gravityAt(s,{x:10,y:0}).x,-1);near(N.gravityAt(s,{x:20,y:0}).x,-.25);near(N.gravityAt(s,{x:1,y:0}).x,-12.5);near(N.gravityAt(s,{x:0,y:0}).x,0);});
test('A free gravity source receives the equal and opposite reaction force',()=>{const s=N.empty();s.gravityModel='planets';const planet=N.body('planet',0,0,{r:1,mass:10/N.G,fixed:false}),b=N.body('circle',10,0,{mass:2,r:.1});s.bodies=[planet,b];const sim=new N.Simulation(s);sim.step();const p=sim.state(planet.id),q=sim.state(b.id);near(p.mass*p.vx+q.mass*q.vx,0,1e-10);near(q.ax,-.1,1e-8);near(sim.bodies.get(planet.id).reaction.x,0,1e-8);});
test('Vacuum orbit conserves energy in a nearby fixed inverse-square field',()=>{const s=N.empty();s.gravityModel='planets';const p=N.body('planet',0,0,{r:2,mass:100/N.G,fixed:true}),b=N.body('circle',10,0,{r:.1,vy:Math.sqrt(10)});s.bodies=[p,b];const sim=new N.Simulation(s),energy=()=>{const v=sim.state(b.id);return .5*v.speed*v.speed-100/Math.hypot(v.x,v.y);},initial=energy();sim.advance(20);near(energy(),initial,.002);});
test('Finite refueling conserves contents, respects capacity, range and docking speed',()=>{const s=N.empty();s.gravity=0;const station=N.body('refuel',0,0,{fixed:true,fuelStore:3,oxygenStore:16,fuelRate:1,oxygenRate:8,refuelRadius:3}),fuel=N.equipment('fuel',1,0,{contents:0,capacity:2}),oxygen=N.equipment('oxygen',1,1,{contents:0,capacity:8});s.bodies=[station,fuel,oxygen];const sim=new N.Simulation(N.validate(s));sim.advance(3);near(sim.bodies.get(fuel.id).spec.contents,2);near(sim.bodies.get(oxygen.id).spec.contents,8);near(sim.bodies.get(station.id).spec.fuelStore,1);near(sim.bodies.get(station.id).spec.oxygenStore,8);near(sim.bodies.get(fuel.id).body.getMass(),4);fuel.vx=3;const fast=new N.Simulation(s);fast.advance(.1);near(fast.bodies.get(fuel.id).spec.contents,0);fuel.vx=0;fuel.x=10;const far=new N.Simulation(s);far.advance(.1);near(far.bodies.get(fuel.id).spec.contents,0);});
test('Moving donor refueling transfers linear momentum without inventing propellant',()=>{const s=N.empty();s.gravity=0;const station=N.body('refuel',0,0,{fixed:false,mass:2,vx:1,fuelStore:2,oxygenStore:0,fuelRate:1,oxygenRate:0,refuelRadius:3}),tank=N.equipment('fuel',1,0,{mass:2,contents:0,capacity:2,vx:0});s.bodies=[station,tank];const sim=new N.Simulation(s),momentum=()=>[...sim.bodies.values()].reduce((sum,e)=>sum+e.body.getMass()*e.body.getLinearVelocity().x,0),initial=momentum();sim.advance(.1);near(momentum(),initial,1e-9);near(sim.bodies.get(station.id).spec.fuelStore+sim.bodies.get(tank.id).spec.contents,2);});
test('The new examples validate and use separate engines, tanks, motors and finite stations',()=>{for(const type of ['spaceTour','roughCourse']){const s=Workshop.example(type);N.validate(s);const sim=new N.Simulation(s);sim.keys.add(type==='spaceTour'?'w':'d');sim.advance(2);assert.ok(Number.isFinite(sim.state(s.subject).x));assert.ok(s.bodies.some(b=>b.kind==='refuel'));if(type==='spaceTour'){assert.equal(s.bodies.filter(b=>b.kind==='planet').length,3);assert.deepEqual(s.bodies.filter(b=>b.kind==='thruster').map(b=>b.thrusters[0].key).sort(),['a','d','s','w']);assert.ok(sim.state(s.subject).y>0);}else assert.equal(s.joints.filter(j=>j.motorBodyId).length,2);}});
test('Trajectory buffers retain a full forever span with bounded storage and expire fading rows',()=>{const tr=new Workshop.Trail();for(let i=0;i<20000;i++)tr.sample(i,0,i*.05,0);assert.ok(tr.length<=8192);near(tr.data[2],0);const last=(tr.start+tr.length-1)%8192;near(tr.data[last*3],19999);const faded=new Workshop.Trail();for(let i=0;i<1000;i++)faded.sample(i,0,i*.05,2);assert.ok(faded.length<=42);});
test('Invalid trajectory, material, station and motor link data is rejected',()=>{const s=Workshop.example('roughCourse');s.materials=[{name:'Broken',density:-1,friction:.4}];assert.throws(()=>N.validate(s));delete s.materials;s.bodies.find(b=>b.kind==='refuel').fuelRate=Infinity;assert.throws(()=>N.validate(s));const q=Workshop.example('spaceTour');q.bodies.at(-1).trace.width=100;assert.throws(()=>N.validate(q));});
console.log(count+' workshop physics checks passed.');
