(function(root){
'use strict';const N=root.Newton, B=N.body;
function base(gravity=0,air=false){return {...N.empty(),gravity,air};}
function block(extra={}){return B('rectangle',0,3,{w:1,h:1,mass:2,friction:0,restitution:0,color:'#5f86ff',...extra});}
function forceScene(extra,g=0){const s=base(g);s.bodies=[block(extra)];return s;}
function projectile(speed,angle){const s=base(9.81);s.bodies=[B('launcher',0,0,{w:1.2,h:.5,launchSpeed:speed,launchAngle:angle,projectileMass:1,projectileRadius:.12,fireKey:'f',dragK:.02,color:'#35bba3'}),B('ground',10,-.65,{w:40,h:1,color:'#526276'})];return s;}
const levels=[
 {title:'Mass matters',topic:'Newton’s second law',prompt:'A 12 N horizontal force acts in zero gravity. Choose a mass that gives 3 m/s² of acceleration.',hint:'F = ma, so m = F ÷ a.',variable:'mass',label:'Mass',unit:'kg',min:.1,max:20,start:2,target:3,duration:1,metric:'ax',scene:()=>forceScene({fx:12})},
 {title:'Choose the force',topic:'Newton’s second law',prompt:'Accelerate a 5 kg block at 2 m/s² to the right. Change only the horizontal force.',hint:'Net force = mass × acceleration.',variable:'fx',label:'Horizontal force',unit:'N',min:0,max:100,start:4,target:2,duration:1,metric:'ax',scene:()=>forceScene({mass:5,fx:4})},
 {title:'Hold a hover',topic:'Balanced forces',prompt:'Keep a 2 kg block at the same height on Earth. Choose the upward force. The block starts at rest.',hint:'For a hover, upward force equals weight: F = mg. Earth g = 9.81 m/s².',variable:'fy',label:'Upward force',unit:'N',min:0,max:80,start:10,target:3,duration:2,metric:'y',tolerance:.08,scene:()=>forceScene({mass:2,fy:10},9.81)},
 {title:'Two forces',topic:'Net force',prompt:'A thruster pushes left with 8 N. The block has mass 3 kg. Choose a rightward force for a net acceleration of 2 m/s².',hint:'Right force − left force = ma.',variable:'fx',label:'Rightward force',unit:'N',min:0,max:60,start:8,target:2,duration:1,metric:'ax',scene:()=>forceScene({mass:3,fx:8,thrusters:[{force:8,angle:180,key:'a',always:true,offsetX:0,offsetY:0}]})},
 {title:'Travel four meters',topic:'Displacement',prompt:'A 2 kg block starts at rest in zero gravity. Move it 4 m to the right in 2 s by choosing a constant force.',hint:'Δx = ½at² and F = ma.',variable:'fx',label:'Horizontal force',unit:'N',min:0,max:40,start:2,target:4,duration:2,metric:'x',scene:()=>forceScene({mass:2,fx:2})},
 {title:'Coast to the marker',topic:'Constant velocity',prompt:'With no net force, travel 9 m in 3 s. Choose the initial horizontal velocity.',hint:'Δx = vt when acceleration is zero.',variable:'vx',label:'Initial velocity x',unit:'m/s',min:0,max:15,start:1,target:9,duration:3,metric:'x',scene:()=>forceScene({vx:1})},
 {title:'Gentle braking',topic:'Negative acceleration',prompt:'A 4 kg block starts moving right at 6 m/s. Bring it to rest exactly after 2 s using a constant horizontal force.',hint:'a = (vfinal − vinitial) ÷ t. A leftward force is negative.',variable:'fx',label:'Horizontal force',unit:'N',min:-60,max:0,start:-4,target:0,duration:2,metric:'vx',tolerance:.08,scene:()=>forceScene({mass:4,vx:6,fx:-4})},
 {title:'Moon rise',topic:'Gravity and net force',prompt:'On the Moon (g = 1.62 m/s²), make a 3 kg block accelerate upward at 1 m/s².',hint:'Fup − mg = ma. Use the Moon’s gravity.',variable:'fy',label:'Upward force',unit:'N',min:0,max:50,start:5,target:1,duration:1,metric:'ay',scene:()=>forceScene({mass:3,fy:5},1.62)},
 {title:'Launch for range',topic:'Projectile motion',prompt:'Launch at 45° on Earth. Land at x = 10 m when the center returns to its launch height. Choose launch speed; air resistance is off.',hint:'For equal launch and landing heights, R = v²sin(2θ) ÷ g.',variable:'launchSpeed',label:'Launch speed',unit:'m/s',min:1,max:25,start:6,target:10,duration:6,metric:'range',scene:()=>projectile(6,45)},
 {title:'Aim the launcher',topic:'Projectile motion',prompt:'Launch at 12 m/s on Earth and return to launch height at x = 10 m. Find the lower launch angle (5°–44°).',hint:'sin(2θ) = Rg ÷ v². Use the smaller angle.',variable:'launchAngle',label:'Launch angle',unit:'°',min:5,max:44,start:35,target:10,duration:6,metric:'range',scene:()=>projectile(12,35)},
 {title:'Terminal speed',topic:'Air resistance',prompt:'Quadratic drag has k = 1 kg/m. Choose the falling mass so terminal downward speed is 5 m/s on Earth. Observe speed after 5 s.',hint:'At terminal speed, mg = kv². Drag magnitude = kv².',variable:'mass',label:'Mass',unit:'kg',min:.1,max:15,start:1,target:5,duration:5,metric:'speed',scene:()=>{const s=base(9.81,true);s.bodies=[B('circle',0,15,{mass:1,dragK:1})];return s;}},
 {title:'Spin one revolution',topic:'Motor speed',prompt:'An anchored motor turns a light wheel. Set motor speed so the wheel makes 1 revolution in 2 s. Torque limit is fixed at 100 N·m.',hint:'rpm = revolutions ÷ seconds × 60. A real motor takes a brief time to accelerate.',variable:'rpm',label:'Motor speed',unit:'rpm',min:1,max:120,start:15,target:2*Math.PI,duration:2,metric:'angle',scene:()=>{const s=base();const b=B('gear',0,3,{mass:.1,r:1,teeth:20});s.bodies=[b];s.joints=[{id:'motor',kind:'axle',a:null,b:b.id,x:0,y:3,motor:true,auto:true,rpm:15,torque:100,keyPositive:'d',keyNegative:'a'}];return s;}},
 {title:'Gear reduction',topic:'Gears',prompt:'An 8-tooth driver turns at 120 rpm. Choose driven gear teeth to produce 24 rpm in the opposite direction. Both axles are fixed.',hint:'Driver rpm × driver teeth = driven rpm × driven teeth.',variable:'teeth',label:'Driven gear teeth',unit:'teeth',min:8,max:80,start:16,target:24,duration:2,metric:'gearRPM',scene:()=>{const s=base();const a=B('gear',-1,3,{r:.5,mass:.1,teeth:8,color:'#ffa64d'}),b=B('gear',1,3,{r:1,mass:.2,teeth:16});s.bodies=[a,b];s.joints=[{id:'drive',kind:'axle',a:null,b:a.id,x:-1,y:3,motor:true,auto:true,rpm:120,torque:100,keyPositive:'d',keyNegative:'a'},{id:'driven',kind:'axle',a:null,b:b.id,x:1,y:3,motor:false,auto:false,rpm:0,torque:0,keyPositive:'l',keyNegative:'j'},{id:'mesh',kind:'gear',a:a.id,b:b.id,joint1:'drive',joint2:'driven',ratio:2}];return s;}},
 {title:'Control the bounce',topic:'Collisions',prompt:'A ball hits a fixed floor at 6 m/s in zero gravity. Choose restitution so it rebounds upward at 3 m/s.',hint:'Restitution e = rebound speed ÷ approach speed. The floor’s restitution is zero.',variable:'restitution',label:'Restitution',unit:'',min:0,max:1,start:.2,target:3,duration:.7,metric:'vy',scene:()=>{const s=base();s.bodies=[B('circle',0,2,{r:.4,vy:-6,restitution:.2,friction:0}),B('ground',0,-.5,{w:20,h:1,restitution:0,friction:0})];return s;}},
 {title:'Share the momentum',topic:'Momentum',prompt:'A block at 5 m/s hits a stationary 2 kg block. They have zero restitution and no friction or external forces. Choose moving mass so their common speed is 3 m/s.',hint:'m₁v₁ + m₂v₂ = (m₁ + m₂)vfinal. The collision is inelastic.',variable:'mass',label:'Moving block mass',unit:'kg',min:.1,max:20,start:1,target:3,duration:2,metric:'vx',scene:()=>{const s=base();s.bodies=[block({x:-3,vx:5,mass:1}),block({x:0,mass:2,color:'#ffa64d'})];return s;}}
];
function configure(index,value){const l=levels[index],s=l.scene(),b=s.bodies[0];if(l.variable==='rpm')s.joints[0].rpm=value;else if(l.variable==='teeth'){s.bodies[1].teeth=value;s.joints.find(j=>j.kind==='gear').ratio=value/8;}else b[l.variable]=value;return s;}
function observe(index,sim,range){const l=levels[index];if(l.metric==='range')return range;if(l.metric==='gearRPM')return Math.abs(sim.state(sim.scene.bodies[1].id).omega)*30/Math.PI;return sim.state(sim.scene.bodies[0].id)[l.metric];}
function pass(index,actual){const l=levels[index];return Number.isFinite(actual)&&Math.abs(actual-l.target)<=(l.tolerance||Math.max(.04,Math.abs(l.target)*.025));}
root.Challenges={levels,configure,observe,pass};if(typeof module!=='undefined')module.exports=root.Challenges;
})(typeof window!=='undefined'?window:globalThis);
