/* Engineering missions: every result comes from the live rigid-body simulation. */
(function(root){
'use strict';const N=root.Newton,B=N.body;
const curriculum='engineering-v2';
const axle=(a,b,rpm=90,torque=6,auto=true)=>({id:N.uid(),kind:'axle',a:a?.id||null,b:b.id,x:b.x,y:b.y,motor:true,auto,rpm,torque,keyPositive:'a',keyNegative:'d'});
function road(hill=false){const s=N.empty();for(let i=-2;i<30;i++){const t=N.terrain(i*80,0,80,160);t.base=-30;t.profile=t.profile.map((_,j)=>{const x=i*80-40+j*.5;return hill?Math.max(0,Math.min(12,(x-8)*.24)):0;});s.bodies.push(t);}s.follow=true;return s;}
function addCar(s,x=0,options={}){const wheels=options.wheels||2,ballast=options.ballast||0,chassis=B('rectangle',x,1.25,{w:2.4*wheels-1.2,h:.55,mass:8+ballast,restitution:0,friction:.6,color:options.color||'#35bba3',name:options.name||'Rover'});s.bodies.unshift(chassis);const box=N.equipment('gearbox',x,1.9,{mass:1,ratio:options.ratio||1,mountId:chassis.id});s.bodies.push(box);for(let i=0;i<wheels;i++){const px=x-1.2*(wheels-1)+i*2.4,wheel=B('circle',px,.61,{r:.6,mass:1,friction:options.friction??.8,restitution:0,color:'#526276'});s.bodies.push(wheel);const j=axle(chassis,wheel,options.rpm||100,options.torque||6,options.auto??true);j.rpm=-(options.rpm||100);j.keyPositive='d';j.keyNegative='a';j.gearboxId=box.id;s.joints.push(j);}return chassis;}
function gearScene(teeth=40){const s=N.empty();s.gravity=0;const a=B('gear',0,3,{r:.5,teeth:8,mass:.2,color:'#ffa64d'}),b=B('gear',.5+.5*teeth/8,3,{r:.5*teeth/8,teeth,mass:.3});s.bodies=[a,b];s.joints=[{...axle(null,a,120,200),id:'drive'},{...axle(null,b,0,0),motor:false,id:'driven'},{id:'mesh',kind:'gear',a:a.id,b:b.id,joint1:'drive',joint2:'driven',ratio:teeth/8}];s.subject=b.id;return s;}
function launchScene(speed=20,angle=35){const s=N.empty(),l=B('launcher',0,1,{w:1.2,h:.45,launchSpeed:speed,launchAngle:angle,projectileMass:.2,projectileRadius:.12,fireKey:'f',aimPositiveKey:'i',aimNegativeKey:'k',aimRate:30,dragK:0,color:'#35bba3'});s.bodies=[l,B('ground',30,-.65,{w:100,h:1,restitution:0})];s.subject=l.id;s.follow=true;s.camera={x:8,y:4,scale:24};s.launch=true;return s;}
function catapult(torque=160,release=.42){const s=N.empty(),arm=B('rectangle',-2,2,{w:4,h:.24,mass:2,color:'#b88756',restitution:0}),payload=B('circle',-4.3,2,{r:.22,mass:.4,color:'#ffa64d',restitution:0,catapultPayload:true});s.bodies=[arm,payload,B('ground',25,-.5,{w:100,h:1,restitution:0}),B('ground',0,.9,{w:.6,h:1.8})];const j=axle(null,arm,-45,torque);j.x=0;j.y=2;j.keyPositive='l';j.keyNegative='j';j.lowerAngle=-1.4;j.upperAngle=.08;s.joints=[j,{id:'payload',kind:'weld',a:arm.id,b:payload.id,x:payload.x,y:payload.y,releaseKey:'f'}];s.subject=payload.id;s.releaseAt=release;s.follow=true;s.camera={x:3,y:4,scale:30};return s;}
function rocket(values={},earth=false){const s=N.empty();s.gravity=earth?9.81:0;s.gravityModel=earth?'earth':'uniform';s.air=false;const hull=B('rectangle',0,3,{w:values.width||1,h:values.height||2,mass:values.dryMass||20,restitution:0,dragK:0,color:'#797ee7',name:'Spacecraft'}),engine=N.equipment('thruster',earth?0:-1.4,earth?1.55:3,{mountId:hull.id,w:.6,h:.7,mass:4}),fuel=N.equipment('fuel',0,earth?3.7:3,{mountId:hull.id,contents:values.fuel??200,mass:3}),oxygen=N.equipment('oxygen',0,earth?2.7:3,{mountId:hull.id,contents:(values.fuel??200)*8,mass:3});engine.thrusters[0].force=values.force??100000;engine.thrusters[0].always=true;engine.thrusters[0].angle=earth?90:0;engine.thrusters[0].exhaustSpeed=earth?4500:250;engine.thrusters[0].oxygenRatio=8;s.bodies=[hull,engine,fuel,oxygen];if(earth)s.bodies.push(B('ground',0,-.5,{w:30,h:1,restitution:0,friction:.8}));s.subject=hull.id;s.follow=true;s.camera={x:0,y:4,scale:40};return s;}
function lift(torque=30){const s=N.empty(),arm=B('rectangle',0,3,{w:3,h:.16,mass:1,restitution:0,color:'#b88756'}),load=B('rectangle',1.6,3,{w:.5,h:.5,mass:6,restitution:0,color:'#ffa64d'});s.bodies=[arm,load,B('ground',0,-.5,{w:20,h:1})];const j=axle(null,arm,15,torque);j.x=-1.5;j.y=3;j.keyPositive='u';j.keyNegative='j';j.lowerAngle=-.15;j.upperAngle=.7;s.joints=[j,{id:'load',kind:'weld',a:arm.id,b:load.id,x:load.x,y:load.y}];s.subject=load.id;return s;}
function tug(v){const s=road(),ours=addCar(s,0,{wheels:v.wheels,ballast:v.ballast,torque:v.torque,rpm:50,name:'Your blue car',color:'#5f86ff'}),rival=addCar(s,7,{wheels:2,ballast:14,torque:25,rpm:-50,name:'Opponent',color:'#e78a50'});s.subject=ours.id;s.joints.push({id:'tug',kind:'rod',a:ours.id,b:rival.id,x:3.5,y:1.25,length:7});s.budget=v.wheels*2+v.ballast+v.torque/2;return s;}
const f=(key,label,unit,min,max,start,step=.1)=>({key,label,unit,min,max,start,step});
const levels=[
 {title:'Hill rescue: motor torque',topic:'Torque, traction & gravity',fields:[f('torque','Each motor’s maximum torque','N·m',1,35,3)],duration:16,target:55,metric:'x',rule:'atLeast',locked:'11 kg rover including wheels/gearbox; 0.6 m wheels; μ = 0.8; 100 rpm; rise 12 m over 50 m.',prompt:'Reach the plateau at x ≥ 55 m in 16 s. Choose enough torque to lift the rover uphill without assuming unlimited tire grip.',make:v=>{const s=road(true);s.subject=addCar(s,0,{torque:v.torque}).id;return s;},hint:'At steady climb, total wheel force must overcome the downhill component of weight. Wheel force is limited by both torque/radius and friction.'},
 {title:'Hill rescue: choose a gearbox',topic:'Ideal gearing & motor limits',fields:[f('ratio','Gear reduction (input turns / output turn)',':1',.5,8,1)],duration:24,target:55,metric:'x',rule:'atLeast',locked:'Each input motor: 4 N·m, 240 rpm. Same hill, mass and tire friction as mission 1.',prompt:'Reach x ≥ 55 m in 24 s. Reduction multiplies wheel torque but divides wheel rpm. Too little stalls; too much misses the deadline.',make:v=>{const s=road(true);s.subject=addCar(s,0,{torque:4,rpm:240,ratio:v.ratio}).id;return s;},hint:'Output torque = input torque × reduction; output rpm = input rpm ÷ reduction. Mechanical power is conserved by ideal gearing.'},
 {title:'Express rover',topic:'Gear ratios & speed',fields:[f('ratio','Gear reduction',':1',.5,8,4)],duration:18,target:100,metric:'x',rule:'atLeast',locked:'Flat road; 240 rpm input; 15 N·m per motor; μ = 0.8.',prompt:'Deliver supplies 100 m down the road within 18 s. The view follows the rover well beyond one window.',make:v=>{const s=road();s.subject=addCar(s,0,{torque:15,rpm:240,ratio:v.ratio}).id;return s;},hint:'Approximate rolling speed = wheel angular speed × radius. Very low reductions may still be torque-limited during acceleration.'},
 {title:'Grip the hillside',topic:'Contact friction',fields:[f('friction','Tire friction coefficient μ','',.02,1.5,.02,.01)],duration:16,target:55,metric:'x',rule:'atLeast',locked:'Terrain μ = 0.7; each motor 25 N·m and 100 rpm. Engine combines contact μ as √(μtire × μterrain).',prompt:'Reach x ≥ 55 m by changing the tire compound. More motor torque alone cannot fix tires that slip.',make:v=>{const s=road(true);s.subject=addCar(s,0,{torque:25,friction:v.friction}).id;return s;},hint:'Maximum tangential contact force is μcontact times normal force. Weight on the slope supplies the normal force.'},
 {title:'Lift the rescue crate',topic:'Torque & lever arms',fields:[f('torque','Lifting motor torque','N·m',1,300,30)],duration:4,target:4.6,metric:'y',rule:'atLeast',locked:'6 kg crate on a 3.1 m lever arm; 1 kg beam; 15 rpm motor; no rope model.',prompt:'Raise the crate center to y ≥ 4.6 m in 4 s. The motor rotates a rigid lifting arm; gravity and the crate’s mass are real.',make:v=>lift(v.torque),hint:'Torque required near the starting position is approximately crate weight × lever arm, plus the beam’s own weight torque.'},
 {title:'Slow the observatory gear',topic:'Ideal gear reduction',fields:[f('teeth','Driven gear teeth','teeth',8,80,16,1)],duration:2,target:24,metric:'gearRPM',tolerance:1,locked:'8-tooth driver, 120 rpm, fixed neighboring axles; driven radius follows tooth count.',prompt:'Make the observatory gear rotate at 24 rpm in the opposite direction.',make:v=>gearScene(v.teeth),hint:'Driver teeth × driver rpm = driven teeth × driven rpm.'},
 {title:'Fast scanner',topic:'Ideal gear speed',fields:[f('teeth','Driven gear teeth','teeth',6,40,24,1)],duration:2,target:160,metric:'gearRPM',tolerance:3,locked:'8-tooth input gear, 120 rpm, sufficiently strong motor; no gear tooth losses.',prompt:'Choose a smaller neighboring output gear to turn the scanner at 160 rpm.',make:v=>gearScene(v.teeth),hint:'To go faster, the output gear needs fewer teeth than the driver.'},
 {title:'Aim at the rescue buoy',topic:'Projectile trajectory',fields:[f('angle','Launcher angle','°',5,80,45)],duration:5,target:25,metric:'range',tolerance:1,locked:'20 m/s muzzle speed; target x = 25 m at the 1 m launch height; air off.',prompt:'Hit the target-height crossing within 1 m of x = 25 m. Test fires exactly one shot; aim keys I/K and fire F work in the matching Explore example.',make:v=>launchScene(20,v.angle),hint:'For equal heights, R = v² sin(2θ) / g. Either valid angle can work.'},
 {title:'Long-range supply launcher',topic:'Projectile range',fields:[f('speed','Launch speed','m/s',5,45,12)],duration:7,target:60,metric:'range',tolerance:2,locked:'45° angle; target at original height; 0.2 kg pod; gravity 9.81 m/s²; air off.',prompt:'Send a supply pod to x = 60 m within 2 m. The camera follows the projectile beyond the starting view.',make:v=>launchScene(v.speed,45),hint:'At 45°, range = speed² / g. Mass does not change the vacuum trajectory.'},
 {title:'Build a siege catapult',topic:'Rotational launch & timing',fields:[f('torque','Arm motor torque','N·m',30,300,80),f('release','Payload release time','s',.15,.75,.42,.01)],duration:6,target:10,metric:'landing',tolerance:2,locked:'4 m beam, mass 2 kg; 0.4 kg payload; 45 rpm maximum; pivot fixed; release weld has key F.',prompt:'Tune strength and release timing so the payload first lands at x = 10 ± 2 m. Launch velocity comes from the rotating arm, not a preset shot.',make:v=>catapult(v.torque,v.release),hint:'Too early sends the payload upward; too late makes it nearly horizontal. Torque affects acceleration before release.'},
 {title:'A tank that lasts',topic:'Thrust, propellant & mass',fields:[f('fuel','Fuel loaded into attached tank','kg',.02,4,.1,.01)],duration:8,target:80,metric:'x',rule:'atLeast',locked:'Zero gravity; 600 N thruster, 250 m/s exhaust; oxygen load = 8 × fuel; hull 20 kg + hardware 10 kg.',prompt:'Reach x ≥ 80 m in 8 s. Add enough propellant, but remember fuel and oxygen increase vehicle mass. No thrust after either tank empties.',make:v=>rocket({force:600,fuel:v.fuel}),hint:'Exhaust mass flow = thrust / exhaust speed. Fuel and oxygen leave together; extra propellant adds inertia.'},
 {title:'Leave the launch pad',topic:'Thrust-to-weight',fields:[f('force','Rocket thrust','N',10,5000,100)],duration:6,target:80,metric:'y',rule:'atLeast',locked:'20 kg hull + 10 kg hardware + 1 kg fuel + 8 kg oxygen; Earth gravity; vacuum model.',prompt:'Climb to y ≥ 80 m in 6 s. This is liftoff, not escape from Earth. Engine thrust must first overcome the complete vehicle’s weight.',make:v=>rocket({force:v.force,fuel:1},true),hint:'Starting weight uses hull + engine + tank dry masses + propellant. Initial net acceleration ≈ (thrust − weight) / total mass.'},
 {title:'Escape Earth',topic:'Inverse-square gravity & energy',fields:[f('force','Rocket thrust','N',1000,200000,10000,100)],duration:60,target:0,metric:'escape',rule:'atLeast',locked:'20 kg hull + 10 kg hardware; 200 kg hydrogen fuel + 1600 kg oxygen; effective exhaust 4500 m/s; no atmosphere.',prompt:'Reach outward flight with nonnegative orbital energy by 60 s. Earth gravity decreases with distance. “Escape margin” = speed − local escape speed; reach ≥ 0 m/s.',make:v=>rocket({force:v.force,fuel:200},true),hint:'Local escape speed = √(2GM/r). A high speed while engines burn is not enough unless it reaches this threshold; gravity losses depend on burn time.'},
 {title:'Budget tug-of-war build',topic:'Resources, mass & traction',fields:[f('wheels','Number of powered wheels','',2,4,2,1),f('ballast','Chassis ballast','kg',0,18,0,1),f('torque','Torque per wheel motor','N·m',2,30,6)],duration:10,target:-6,metric:'tug',rule:'atMost',locked:'Budget ≤ 30 tokens: 2 per wheel + 1 per kg ballast + torque/2. Rival: 2 wheels, 22 kg chassis, 25 N·m each; tire μ = 0.8.',prompt:'Assemble a car from 2–4 powered wheels, ballast and motor strength. Pull your starting center from x = 0 to x ≤ −6 m while the rival pulls right. The connecting rod is rigid and massless.',make:v=>{const s=tug(v);for(const j of s.joints.filter(j=>j.kind==='axle'))j.rpm*=-1;return s;},constraints:v=>v.wheels*2+v.ballast+v.torque/2<=30,hint:'More weight can increase available traction, but uses budget and raises inertia. More wheels spread normal force; they do not create free grip.'},
 {title:'Design an escape spacecraft',topic:'Vehicle design & rocket equation',fields:[f('width','Hull width','m',.5,3,2),f('height','Hull height','m',1,5,4),f('fuel','Fuel tank load','kg',30,250,50,1),f('force','Thruster force','N',10000,200000,30000,100)],duration:65,target:0,metric:'escape',rule:'atLeast',locked:'Hull dry mass = 8 × width × height kg; 10 kg hardware; oxygen = 8 × fuel; fuel ≤ 100 × hull area; thrust ≤ 60,000 × hull area; no atmosphere.',prompt:'Build a spacecraft within tank-space and engine-size limits. Achieve an escape margin ≥ 0 m/s. Keep the hull light enough while providing room for propellant and the engine.',make:v=>rocket({...v,dryMass:8*v.width*v.height},true),constraints:v=>v.fuel<=100*v.width*v.height&&v.force<=60000*v.width*v.height,hint:'Ideal Δv = exhaust speed × ln(start mass / dry mass), before gravity losses. A larger hull has room for tanks but adds dry mass.'}
];
levels.forEach(l=>{const a=l.fields[0];Object.assign(l,{variable:a.key,label:a.label,unit:a.unit,min:a.min,max:a.max,start:a.start,story:l.prompt,hints:['Read the locked quantities, then predict which change helps.',l.hint,'Compare the measured result with the goal. Change one design choice at a time.'],success:'Mission complete — your design met the goal.',steps:['Adjust only the bright controls in the mission card. '+l.locked,l.hint,'The test uses automatic controls so repeated tests are comparable. Explore examples let you drive manually.','Test, watch the camera follow, inspect the result and revise your design.']});});
function values(index,value){const l=levels[index];if(typeof value==='number')return Object.fromEntries(l.fields.map((f,i)=>[f.key,i?f.start:value]));return {...Object.fromEntries(l.fields.map(f=>[f.key,f.start])),...value};}
function valid(index,value){const l=levels[index],v=values(index,value);return l.fields.every(f=>Number.isFinite(v[f.key])&&v[f.key]>=f.min&&v[f.key]<=f.max&&(f.step===1?Number.isInteger(v[f.key]):true))&&(!l.constraints||l.constraints(v));}
function configure(index,value){const v=values(index,value);if(!valid(index,v))throw Error('Design is outside the allowed ranges or resource budget.');const s=levels[index].make(v);s.mission=index;return s;}
function begin(index,sim){const a={index,shot:null,range:null,landing:null,previousLanding:null,released:false,maxX:-Infinity,maxY:-Infinity};if(sim.scene.launch)a.shot=sim.fire(sim.scene.subject).spec.id;else a.shot=sim.scene.subject;return a;}
function tick(index,sim,a){const s=sim.scene,e=sim.bodies.get(a.shot),p=e?.body.getPosition(),q=e?.previous;if(s.releaseAt!==undefined&&!a.released&&sim.time>=s.releaseAt){sim.release('f');a.released=true;}if(!e)return;const v=e.body.getLinearVelocity();a.maxX=Math.max(a.maxX,p.x);a.maxY=Math.max(a.maxY,p.y);if(a.range===null&&s.launch&&sim.time>.04&&q.y>1&&p.y<=1&&v.y<0)a.range=q.x+(p.x-q.x)*(q.y-1)/(q.y-p.y);if(a.landing===null&&a.released&&q.y>e.spec.r+.02&&p.y<=e.spec.r+.02&&v.y<0)a.landing=q.x+(p.x-q.x)*(q.y-e.spec.r-.02)/(q.y-p.y);}
function observe(index,sim,a){const l=levels[index],e=sim.bodies.get(sim.scene.subject||sim.scene.bodies[0].id),p=e.body.getPosition(),v=e.body.getLinearVelocity();if(l.metric==='range')return a?.range;if(l.metric==='landing')return a?.landing;if(l.metric==='gearRPM')return Math.abs(e.body.getAngularVelocity())*30/Math.PI;if(l.metric==='escape'){const y=p.y+N.EARTH_RADIUS,r=Math.hypot(p.x,y),outward=(p.x*v.x+y*v.y)/r;return outward>0?v.length()-Math.sqrt(2*N.EARTH_MU/r):-Math.sqrt(2*N.EARTH_MU/r);}if(l.metric==='tug')return p.x;return sim.state(e.spec.id)[l.metric];}
function pass(index,actual){const l=levels[index];return Number.isFinite(actual)&&(l.rule==='atLeast'?actual>=l.target:l.rule==='atMost'?actual<=l.target:Math.abs(actual-l.target)<=l.tolerance);}
function run(index,value){const s=new N.Simulation(configure(index,value)),a=begin(index,s);for(let n=0;n<Math.round(levels[index].duration/N.DT);n++){s.step();tick(index,s,a);}return {actual:observe(index,s,a),sim:s,attempt:a};}
function example(name){let s;if(name==='hillCar')s=levels[0].make({torque:15});if(name==='gearCar')s=levels[1].make({ratio:3});if(name==='longRoad')s=levels[2].make({ratio:1});if(name==='lift')s=lift(230);if(name==='rocket')s=rocket({force:3000,fuel:8},true);if(name==='escapeRocket')s=rocket({force:120000,fuel:200},true);if(name==='tug')s=tug({wheels:2,ballast:8,torque:20});if(s){delete s.mission;for(const j of s.joints)if(j.motor)j.auto=false;for(const b of s.bodies)for(const t of b.thrusters)t.always=false;return s;}return null;}
root.Challenges={levels,curriculum,values,valid,configure,observe,pass,begin,tick,run,example,gearScene,launchScene,rocket,catapult,road,addCar};if(typeof module!=='undefined')module.exports=root.Challenges;
})(typeof window!=='undefined'?window:globalThis);
