/* Building tools. Physics stays in physics.js; trails never feed the solver. */
(function(root){
'use strict';
const materials=[{name:'Lightweight solid',density:100,friction:.4},{name:'Wood',density:650,friction:.5},{name:'Aluminum',density:2700,friction:.35},{name:'Rubber',density:1100,friction:.9}];
const dock={visible:true,collapsed:false,position:'below'};
function assembly(id){const ids=sim.bodies.get(id)?.assemblyIds;return scene.bodies.filter(b=>b.id!==id&&ids?.has(b.id));}
function anchors(host,before,joints,parts){const ids=new Set([host.id,...parts.map(b=>b.id)]),a=host.angle-before.angle,c=Math.cos(a),s=Math.sin(a);for(const old of joints){if(!ids.has(old.b))continue;const j=scene.joints.find(j=>j.id===old.id);if(!j)continue;const x=old.x-before.x,y=old.y-before.y;j.x=host.x+c*x-s*y;j.y=host.y+s*x+c*y;}}
function resizeBody(b,before){Newton.resizeMass(b,before);if(b.kind==='motor'){for(const j of scene.joints)if(j.motorBodyId===b.id)j.torque=(before.motorTorque??j.torque)*Newton.area(b)/Newton.area(before);}
 const valid=b.mass<=Newton.massLimit(b)&&b.mass>=.01&&b.thrusters.every(t=>Math.abs(t.force)<=1e6)&&(!['fuel','oxygen'].includes(b.kind)||b.capacity<=5000);
 if(!valid){Object.assign(b,before);return false;}return true;}
function ready(b,fresh=false){const N=Newton;if(fresh)N.prepareSizing(b,b.kind==='point'?b.mass/N.volume(b):b.kind==='thruster'?300:b.kind==='motor'?300:100,b.kind==='thruster'||b.kind==='motor'?'Hollow actuator hardware':'Lightweight solid');else N.prepareSizing(b);if(fresh)N.resizeMass(b);if(['fuel','oxygen'].includes(b.kind))b.capacity??=b.contents;return b;}
function addMotor(j){if(!j.motor||j.motorBodyId)return;if(scene.bodies.length>=180){j.motor=false;toast('Make room for motor hardware: maximum 180 objects.');return;}const b=Newton.body('motor',j.x,j.y,{r:.18,w:.36,h:.36,mass:.61,mountId:j.a||undefined,fixed:!j.a,color:'#d69f43',motorTorque:j.torque,name:'Motor housing'});ready(b,true);scene.bodies.push(b);j.motorBodyId=b.id;}
function settleMotor(j){const b=scene.bodies.find(b=>b.id===j.motorBodyId);if(b)b.motorTorque=j.torque;}
function normalize(){if(mode!=='explore')return;for(const b of scene.bodies){ready(b);if(b.autoMass)Newton.resizeMass(b);}for(const j of scene.joints)settleMotor(j);}
function applyDock(remember=true){
 const panel=$('connectPanel'),side=dock.position==='right';if(side)$('workspace').insertBefore(panel,document.querySelector('.stage'));else $('connectBelowSlot').append(panel);
 panel.hidden=!dock.visible||mode!=='explore';panel.classList.toggle('is-minimized',dock.collapsed);$('connectPanelContent').hidden=dock.collapsed;$('collapseConnect').textContent=dock.collapsed?'Expand':'Minimize';$('collapseConnect').setAttribute('aria-expanded',String(!dock.collapsed));$('connectDock').value=dock.position;
 $('workspace').classList.toggle('connect-right',side&&dock.visible&&mode==='explore');$('connectToggle').setAttribute('aria-pressed',String(dock.visible));$('connectToggle').disabled=mode!=='explore';
 if(remember)try{localStorage.setItem('newton-studio-connect-layout',JSON.stringify(dock));}catch{}requestAnimationFrame(resize);
}
function materialControls(b){return `<div class="property-section"><h3>Object & material</h3><label class="field">Name<input data-prop="name" maxlength="80" value="${esc(b.name||'')}"></label><label class="check spaced"><input id="fixedObject" type="checkbox" ${Newton.isFixed(b)?'checked':''}>Fixed in world</label><label class="field spaced">Material<select id="materialSelect"><option value="">${esc(b.materialName||'Custom solid')}</option>${[...materials,...(scene.materials||[])].map((m,i)=>`<option value="${i}">${esc(m.name)} · ${m.density} kg/m³</option>`).join('')}</select></label><div class="property-grid spaced">${field('Density (kg/m³)','density',b.density,.001,1e16,.1)}${b.kind==='planet'?'':field('Thickness (m)','thickness',b.thickness,.001,10,.001)}</div><label class="check spaced"><input id="autoMass" type="checkbox" ${b.autoMass?'checked':''}>Mass follows density and size</label><button id="newMaterial" class="spaced">Save named material…</button><p class="small">${b.kind==='planet'?'Planet mass uses density × sphere volume.':'Mass = density × area × thickness. Tank contents add their own mass.'}</p><p class="small">Dry mass: ${fmt(b.mass)} kg.</p></div>`;}
function inspector(b){let html=materialControls(b);
 html+=`<div class="property-section"><h3>Trajectory ${b.kind==='point'?'point':''}</h3><label class="check"><input id="traceEnabled" type="checkbox" ${b.trace?.enabled?'checked':''}>Show trajectory line</label><div class="property-grid spaced"><label class="field">Line color<input id="traceColor" type="color" value="${b.trace?.color||'#d46cff'}"></label><label class="field">Thickness (px)<input id="traceWidth" type="number" min=".5" max="12" step=".5" value="${b.trace?.width||2}"></label><label class="field full">Fade after (simulation seconds)<input id="traceFade" type="number" min="0" max="600" step="1" value="${b.trace?.fade??10}"></label></div><p class="small">0 keeps the path until Reset. Weld a point to a moving object to trace that location.</p><button id="addTracePoint">+ Attach trajectory point here</button></div>`;
 if(b.kind==='motor'){const j=scene.joints.find(j=>j.motorBodyId===b.id);html+=`<div class="property-section"><h3>Motor hardware</h3><p class="small">${j?'Rated torque: '+fmt(j.torque)+' N·m. Resize this housing to scale its mass and torque with area. Set speed and key controls below.':'Motor housing; its axle has been removed.'}</p></div>`;}
 if(b.kind==='planet')html+=`<div class="property-section"><h3>Gravity source</h3><p class="small">Surface gravity: ${fmt(Newton.G*b.mass/b.r**2)} m/s². Select Nearby worlds gravity to use these sources. Fixed centers are supported externally; free planets respond to reaction forces.</p></div>`;
 if(b.kind==='refuel')html+=`<div class="property-section"><h3>Refueling station</h3><div class="property-grid">${field('Fuel supply (kg)','fuelStore',b.fuelStore,0,5000)}${field('Oxygen supply (kg)','oxygenStore',b.oxygenStore,0,5000)}${field('Fuel rate (kg/s)','fuelRate',b.fuelRate,0,100)}${field('Oxygen rate (kg/s)','oxygenRate',b.oxygenRate,0,100)}${field('Reach (m)','refuelRadius',b.refuelRadius,.1,20)}</div><p class="small">Pause near the station: tank speed relative to the station must be at most 2 m/s. Finite supplies refill tanks to capacity. Set either rate to 0 to dispense only the other resource.</p></div>`;
 const parts=scene.bodies.filter(a=>a.mountId===b.id);if(parts.length)html+=`<div class="property-section"><h3>Attached parts</h3>${parts.map(a=>`<button class="part-link" data-part="${a.id}">${esc(a.name||a.kind)} → Inspect</button>`).join('')}</div>`;
 return html;
}
function edit(action){if(running||mode!=='explore'){toast('Pause in Explore before changing the world.');updateInspector();return;}checkpoint();editFromLive();action();changed();}
function bind(b){
 $('fixedObject').onchange=()=>{const fixed=$('fixedObject').checked;edit(()=>{const parts=[b,...assembly(b.id)];if(!fixed&&parts.some(p=>p.kind!=='planet'&&p.mass>1000)){toast('Reduce density or thickness before freeing bodies above 1,000 kg.');return;}for(const part of parts)part.fixed=fixed;});};
 $('autoMass').onchange=()=>{const on=$('autoMass').checked;edit(()=>{const old=Newton.copy(b);b.autoMass=on;if(on&&!resizeBody(b,old))toast('Density and size exceed the body mass limit.');});};
 $('materialSelect').onchange=()=>{const m=[...materials,...(scene.materials||[])][Number($('materialSelect').value)];if(!m||$('materialSelect').value==='')return;edit(()=>{const old=Newton.copy(b);b.density=m.density;b.friction=m.friction;b.materialName=m.name;b.autoMass=true;if(!resizeBody(b,old))toast('This material and size exceed the 1,000 kg body limit.');});};
 $('newMaterial').onclick=()=>{if(running)return;openModal('Save a material',`<label class="field">Material name<input id="materialName" maxlength="60" value="${esc(b.materialName)}"></label><p>Density ${fmt(b.density)} kg/m³ · friction ${fmt(b.friction)}</p><button id="saveMaterial" class="run">Save material</button>`);$('saveMaterial').onclick=()=>{const name=$('materialName').value.trim();if(!name)return;edit(()=>{scene.materials??=[];if(scene.materials.length>=30){toast('Maximum 30 custom materials.');return;}scene.materials.push({name,density:b.density,friction:b.friction});b.materialName=name;});$('modal').close();};};
 for(const id of ['traceEnabled','traceColor','traceWidth','traceFade'])$(id).onchange=()=>{const trace={enabled:$('traceEnabled').checked,color:$('traceColor').value,width:Number($('traceWidth').value),fade:Number($('traceFade').value)};if(!Number.isFinite(trace.width)||trace.width<.5||trace.width>12||!Number.isFinite(trace.fade)||trace.fade<0||trace.fade>600){toast('Use a width of 0.5–12 px and fade of 0–600 seconds.');updateInspector();return;}edit(()=>b.trace=trace);};
 $('addTracePoint').onclick=()=>edit(()=>{if(scene.bodies.length>=180)return;const p=Newton.body('point',b.x,b.y,{r:.05,w:.1,h:.1,mass:.01,mountId:b.id,fixed:Newton.isFixed(b),trace:{enabled:true,color:'#d46cff',width:2,fade:10},color:'#d46cff'});if(p.fixed)delete p.mountId;ready(p);scene.bodies.push(p);if(!p.mountId&&Newton.isFixed(b))scene.joints.push({id:Newton.uid(),kind:'weld',a:b.id,b:p.id,x:p.x,y:p.y});selected=p.id;});
 document.querySelectorAll('[data-part]').forEach(el=>el.onclick=()=>{selected=el.dataset.part;updateInspector();});
}
function addSpecial(kind,p){if(!['point','planet','refuel'].includes(kind))return false;edit(()=>{if(scene.bodies.length>=180)return;let b;
 if(kind==='point')b=Newton.body(kind,p.x,p.y,{r:.05,w:.1,h:.1,mass:.01,color:'#d46cff',trace:{enabled:true,color:'#d46cff',width:2,fade:10}});
 if(kind==='planet'){b=Newton.body(kind,p.x,p.y,{r:5,mass:125/Newton.G,fixed:true,color:'#aa7dce',name:'New world'});scene.gravityModel='planets';scene.gravity=0;}
 if(kind==='refuel')b=Newton.body(kind,p.x,p.y,{w:1,h:1.5,fixed:true,fuelStore:50,oxygenStore:400,fuelRate:1,oxygenRate:8,refuelRadius:3,color:'#3aa78e'});
 ready(b,kind!=='planet');scene.bodies.push(b);selected=b.id;});selectTool('select');return true;}
function addThrust(host){edit(()=>{if(scene.bodies.length>=180){toast('Maximum 180 objects.');return;}const offset=host.h/2+.4,c=Math.cos(host.angle),s=Math.sin(host.angle),b=Newton.equipment('thruster',host.x+s*offset,host.y-c*offset,{mountId:host.id,angle:host.angle,fixed:Newton.isFixed(host),name:'Thruster'});ready(b,true);b.thrusters[0].key=freeKey('w');scene.bodies.push(b);selected=b.id;});}
class Trail{
 constructor(){this.data=new Float64Array(8192*3);this.start=0;this.length=0;this.last=-Infinity;}
 sample(x,y,t,fade){if(t-this.last<.049)return;this.last=t;while(fade&&this.length&&t-this.data[this.start*3+2]>fade){this.start=(this.start+1)%8192;this.length--;}
  if(this.length===8192){if(fade){this.start=(this.start+1)%8192;this.length--;}else{for(let i=0;i<4096;i++){const old=(this.start+i*2)%8192;for(let k=0;k<3;k++)this.data[i*3+k]=this.data[old*3+k];}this.start=0;this.length=4096;}}
  const i=(this.start+this.length)%8192;this.data[i*3]=x;this.data[i*3+1]=y;this.data[i*3+2]=t;this.length++;
 }
}
function sampleTrails(){for(const e of sim.bodies.values())if(e.spec.trace?.enabled){e.trail??=new Trail();const p=e.body.getPosition();e.trail.sample(p.x,p.y,sim.time,e.spec.trace.fade);}}
function drawTrails(){ctx.save();for(const e of sim.bodies.values()){const tr=e.trail,style=e.spec.trace;if(!tr||!style?.enabled)continue;ctx.strokeStyle=style.color;ctx.lineWidth=style.width;ctx.lineJoin='round';ctx.lineCap='round';ctx.beginPath();let lastX,lastY,bin=-1;for(let n=0;n<tr.length;n++){const i=(tr.start+n)%8192,age=sim.time-tr.data[i*3+2];if(style.fade&&age>style.fade)continue;const x=(tr.data[i*3]-camera.x)*camera.scale+W/2,y=-(tr.data[i*3+1]-camera.y)*camera.scale+H/2,newBin=style.fade?Math.max(1,Math.ceil(8*(1-age/style.fade))):8;if(lastX===undefined){lastX=x;lastY=y;bin=newBin;ctx.globalAlpha=bin/8;ctx.moveTo(x,y);continue;}if(Math.hypot(x-lastX,y-lastY)<1&&n<tr.length-1)continue;if(newBin!==bin){ctx.stroke();ctx.beginPath();ctx.moveTo(lastX,lastY);bin=newBin;ctx.globalAlpha=bin/8;}if((x<0&&lastX<0)||(x>W&&lastX>W)||(y<0&&lastY<0)||(y>H&&lastY>H))ctx.moveTo(x,y);else ctx.lineTo(x,y);lastX=x;lastY=y;}ctx.stroke();}ctx.restore();}

function glyph(e){const b=e.spec;if(b.kind==='point'){const p=screenPoint(e.renderPosition.x,e.renderPosition.y);ctx.save();ctx.fillStyle=b.color;ctx.strokeStyle=selected===b.id?'#fff':b.color;ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x,p.y,5,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();return true;}return false;}
function details(e){const b=e.spec;if(b.kind==='motor'){ctx.fillStyle='#fbd784';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText('⚙',0,6);ctx.textAlign='start';}
 if(b.kind==='planet'){ctx.strokeStyle='#ffffff55';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,b.r*camera.scale*.7,b.r*camera.scale*.23,.3,0,Math.PI*2);ctx.stroke();ctx.fillStyle=darkTheme?'#e1efff':'#27415b';ctx.textAlign='center';ctx.font='bold 13px system-ui';ctx.fillText(b.name||'World',0,-b.r*camera.scale-12);ctx.textAlign='start';}
 if(b.kind==='refuel'){if(b.w*camera.scale<28){ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 12px system-ui';ctx.fillText('F',0,4);ctx.textAlign='start';return;}ctx.fillStyle='#fff';ctx.textAlign='center';ctx.font='bold 11px system-ui';ctx.fillText('REFUEL',0,-3);ctx.fillText('F '+fmt(b.fuelStore,1)+' · O₂ '+fmt(b.oxygenStore,1),0,13);ctx.textAlign='start';}}
function init(){try{Object.assign(dock,JSON.parse(localStorage.getItem('newton-studio-connect-layout'))||{});}catch{}if(!['below','right'].includes(dock.position))dock.position='below';$('connectToggle').onclick=()=>{dock.visible=!dock.visible;applyDock();};$('collapseConnect').onclick=()=>{dock.collapsed=!dock.collapsed;applyDock();};$('closeConnect').onclick=()=>{dock.visible=false;applyDock();};$('connectDock').onchange=()=>{dock.position=$('connectDock').value;applyDock();};$('gravityModel').onchange=()=>edit(()=>{scene.gravityModel=$('gravityModel').value;if(scene.gravityModel==='planets')scene.gravity=0;});applyDock(false);normalize();updateInspector();}
async function checkedProgress(input){
 const p=restoreProgress(input,false);if(!p.records.length&&!p.legacy?.records.length)return p;
 openModal('Checking saved results','<p id="verificationStatus" role="status">Replaying the locked simulations…</p><p class="small">You can close this window to cancel. Your current scene and progress stay available.</p>');
 for(let index=0;index<p.records.length;index++){
  const record=p.records[index],C=Challenges,n=Math.round(C.levels[record.level].duration/Newton.DT),test=new Newton.Simulation(C.configure(record.level,record.value)),attempt=C.begin(record.level,test);
  let tick=performance.now();for(let i=0;i<n;i++){test.step();C.tick(record.level,test,attempt);if(i%48===0&&performance.now()-tick>8){const status=$('verificationStatus');if(!$('modal').open||!status)throw Error('Result check canceled.');status.textContent=`Checking mission ${index+1} of ${p.records.length} · ${Math.floor(i/n*100)}%`;await new Promise(resolve=>setTimeout(resolve,0));tick=performance.now();}}
  const actual=C.observe(record.level,test,attempt);if(!C.pass(record.level,actual)||Math.abs(actual-record.actual)>Math.max(.1,Math.abs(record.actual)*.03))throw Error('A challenge result could not be reproduced.');
 }
 for(const record of p.legacy?.records||[]){await new Promise(resolve=>setTimeout(resolve,0));if(!$('modal').open||!$('verificationStatus'))throw Error('Result check canceled.');const actual=legacyReplay(record.level,record.value);if(Math.abs(actual-record.actual)>Math.max(.1,Math.abs(record.actual)*.03))throw Error('An original challenge result could not be reproduced.');}
 if(!$('modal').open||!$('verificationStatus'))throw Error('Result check canceled.');$('modal').close();return p;
}
root.Workshop={assembly,anchors,resizeBody,ready,addMotor,settleMotor,normalize,applyDock,inspector,bind,addSpecial,addThrust,sampleTrails,drawTrails,glyph,details,init,Trail,checkedProgress};
})(typeof window!=='undefined'?window:globalThis);
